### ISSUE TITLE
Sample code in the README doesn't work

### ISSUE THREAD

**Issue by tsilvap** [googleapis/nodejs-logging-bunyan#353]
### Environment details

  - OS: Ubuntu 19.04
  - Node.js version: v8.16.1
  - npm version: 6.4.1
  - `@google-cloud/logging-bunyan` version: 1.2.3

#### Steps to reproduce

  1. Set the `GOOGLE_APPLICATION_CREDENTIALS` environment variable to point to file containing service account key, project ID, etc.
  2. Try to run the sample code in the `README`. Namely,
```
const bunyan = require('bunyan');

// Imports the Google Cloud client library for Bunyan
const {LoggingBunyan} = require('@google-cloud/logging-bunyan');

// Creates a Bunyan Stackdriver Logging client
const loggingBunyan = new LoggingBunyan();

// Create a Bunyan logger that streams to Stackdriver Logging
// Logs will be written to: "projects/YOUR_PROJECT_ID/logs/bunyan_log"
const logger = bunyan.createLogger({
  // The JSON payload of the log as it appears in Stackdriver Logging
  // will contain "name": "my-service"
  name: 'my-service',
  streams: [
    // Log to the console at 'info' and above
    {stream: process.stdout, level: 'info'},
    // And log to Stackdriver Logging, logging at 'info' and above
    loggingBunyan.stream('info'),
  ],
});

// Writes some log entries
logger.error('warp nacelles offline');
logger.info('shields at 99%');
```

**Expected result:** The script logs the messages to the console, and then to Stackdriver Logging.

**Actual result:** The script logs the messages to the console, but doesn't log them to Stackdriver Logging. After a few seconds (about 15 seconds on my machine), it throws the following exception:

```
(node:358) UnhandledPromiseRejectionWarning: FetchError: request to http://169.254.169.254/computeMetadata/v1/instance failed, reason: connect EHOSTUNREACH 169.254.169.254:80
    at ClientRequest.<anonymous> (/app/node_modules/node-fetch/lib/index.js:1430:11)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:401:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
(node:358) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:358) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

For the record, I am running the script locally on my machine.

**Comment by bcoe** [comment]
@tsilvap we just pushed a release that will fail in `3s` rather than `15s`, so you would have been able to debug this faster.

To me it sounds like it can't find any authentication methods on your machine, make sure that `GOOGLE_APPLICATION_CREDENTIALS` is set at the time of executing the application, and points to service account JSON that has logging permissions.

**Comment by tsilvap** [comment]
@bcoe It still doesn't work. To be sure, I followed the exact steps in the [Getting Started with Authentication](https://cloud.google.com/docs/authentication/getting-started) page, creating a service account with the role of Owner, and saving the JSON which contains the private key and other metadata to my computer, then setting `GOOGLE_APPLICATION_CREDENTIALS` to the absolute path of the file containing the JSON which I just downloaded.

Also, I added `console.log(process.env['GOOGLE_APPLICATION_CREDENTIALS']` at the end of the script, and it prints out the path of JSON file correctly, so I know the environment variable is set at the time of execution of the script.

I have tried this with two different projects in two different machines, but I still get the same error and the logs don't show up in Stackdriver Logging. Were you not successful in reproducing this behavior?

**Comment by bcoe** [comment]
@tsilvap I'm digging into this myself, and seeing similar issues on my home connection (I wonder if this might be the discrepancy from when I was testing on Friday); I will try to get a patch out the door ASAP for this.

**Comment by mrkiley** [comment]
> @bcoe It still doesn't work. To be sure, I followed the exact steps in the [Getting Started with Authentication](https://cloud.google.com/docs/authentication/getting-started) page, creating a service account with the role of Owner, and saving the JSON which contains the private key and other metadata to my computer, then setting `GOOGLE_APPLICATION_CREDENTIALS` to the absolute path of the file containing the JSON which I just downloaded.
> 
> Also, I added `console.log(process.env['GOOGLE_APPLICATION_CREDENTIALS']` at the end of the script, and it prints out the path of JSON file correctly, so I know the environment variable is set at the time of execution of the script.
> 
> I have tried this with two different projects in two different machines, but I still get the same error and the logs don't show up in Stackdriver Logging. Were you not successful in reproducing this behavior?

FYI: I'm getting the same behavior

**Comment by soldair** [comment]
please see the last linked issue for updates to this issue. it may be resolved now.

**Comment by tsilvap** [comment]
It looks like it is working now, thank you for the quick fix.

**Comment by techieshark** [comment]
I'm seeing something similar, though the exact error is 'socket hang up' not `EHOSTUNREACH`. 

Same issue or different? This is when running the same code as above.

```
(node:64705) UnhandledPromiseRejectionWarning: FetchError: request to http://169.254.169.254/computeMetadata/v1/instance failed, reason: socket hang up
    at ClientRequest.<anonymous> (/.../node_modules/node-fetch/lib/index.js:1455:11)
    at ClientRequest.emit (events.js:198:13)
    at Socket.socketOnEnd (_http_client.js:426:9)
    at Socket.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:64705) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:64705) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by techieshark** [comment]
Update: adding a `resolutions` in the `package.json` to force the use of gcp-metadata version 3 seems to fix the error I was seeing above.

package.json:
```
  "resolutions": {
    "gcp-metadata": "3.0.0"
  }
```

**Comment by edelreal** [comment]
This was the problem for me. I was using the Error Reporting API and the Logging API.

The Error Reporting API would work, but the logging API would fail with

```request to http://169.254.169.254/computeMetadata/v1/instance failed, reason: c
onnect ECONNREFUSED 169.254.169.254:80```

on my local machine,

even though I had correctly set `GOOGLE_APPLICATION_CREDENTIALS` with what I think was a valid credential.

`npm ls gcp-metadata` :

```
└─┬ @google-cloud/logging@7.3.0
  ├── gcp-metadata@3.5.0
  └─┬ google-auth-library@5.3.0
    └── gcp-metadata@3.0.0
```

The resolutions answer above did not work for me.

The solution that worked for me was to delete `node_modules` and run `npm i gcp-metadata`, then `npm i`

This produced this `npm ls gcp-metadata` tree:

```├─┬ @google-cloud/logging@7.3.0
│ ├── gcp-metadata@3.5.0
│ └─┬ google-auth-library@5.3.0
│   └── gcp-metadata@3.5.0
└── gcp-metadata@4.0.0
```
