### ISSUE TITLE
unhandledRejection event using .stream( ) in .createLogger( )

### ISSUE THREAD

**Issue by noguilty4you** [googleapis/nodejs-logging-bunyan#354]
**Point**
Experience some connection issues (on stackdriver service side probably) module throws the unhandled rejections which can be handled only during the process.on('unhandledRejection') . 

**Generated unhandledRejection**
```
FetchError: request to http://169.254.169.254/computeMetadata/v1/instance failed, reason: connect EHOSTDOWN 169.254.169.254:80 - Local (192.168.31.47:55341)
    at ClientRequest.<anonymous> (/Users/**/Documents/projects/**/node_modules/node-fetch/lib/index.js:1455:11)
at ClientRequest.emit (events.js:200:13)
at Socket.socketErrorListener (_http_client.js:402:9)
at Socket.emit (events.js:200:13)
at emitErrorNT (internal/streams/destroy.js:91:8)
at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
at processTicksAndRejections (internal/process/task_queues.js:84:9) {
    message: 'request to http://169.254.169.254/computeMetadata/v1/instance failed, ' +
    'reason: connect EHOSTDOWN 169.254.169.254:80 - Local ' +
    '(192.168.31.47:55341)',
        type: 'system',
        errno: 'EHOSTDOWN',
        code: 'EHOSTDOWN',
        config: {
        url: 'http://169.254.169.254/computeMetadata/v1/instance',
            headers: { 'Metadata-Flavor': 'Google' },
        retryConfig: {
            noResponseRetries: 0,
                currentRetryAttempt: 0,
                retry: 3,
                retryDelay: 100,
                httpMethodsToRetry: [Array],
                statusCodesToRetry: [Array]
        },
        responseType: 'text',
            timeout: 3000,
            params: [Object: null prototype] {},
        paramsSerializer: [Function: paramsSerializer],
        validateStatus: [Function: validateStatus],
        method: 'GET'
    }
}
```

**Start DATE/TIME**
14:03 GMT+0, 14 September 2019

#### ENV
  - OS: **MacOS 10.12.6**  OR **docker: node:current-alpine** OR **docker node:latest**
  - Node.js version: **12.4.0** OR **10.15.3**
  - npm version: **6.11.3**
  - `@google-cloud/logging-bunyan` version: **1.2.3** OR **1.2.2** OR **1.2.1**
  - location: **Moscow, Russia** OR **Moscow, Russia + OpenVPN on FRA1** OR **Kubernetes on FRA1 (DigitalOcean managed cluster)**

#### Steps to reproduce
**App code**
```js
const bunyan = require('bunyan')
  const {LoggingBunyan} = require('@google-cloud/logging-bunyan')

     const loggingBunyan = new LoggingBunyan({
            logName:  config.APP_NAME,
            projectId: config.GOOGLE_STACKDRIVER_PROJECT_ID,  // credentials are ok
            keyFilename: config.GOOGLE_STACKDRIVER_KEYFILE,
        });


        logger = await bunyan.createLogger({
            name: config.APP_NAME,
            streams: [
                loggingBunyan.stream('info'),  // removing this string causes good behavior
            ],
        });
```

**Comment by noguilty4you** [comment]
Another err I've seen just now in kubernetes pod

`GaxiosError: Unsuccessful response status code. Request failed with status code 404
    at Gaxios.request (/home/node/app/node_modules/gaxios/build/src/gaxios.js:70:23)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async metadataAccessor (/home/node/app/node_modules/gcp-metadata/build/src/index.js:47:21)
    at async Object.isAvailable (/home/node/app/node_modules/gcp-metadata/build/src/index.js:97:9)
    at async Object.getEnv (/home/node/app/node_modules/google-auth-library/build/src/auth/envDetect.js:43:18)
    at async Object.getDefaultResource (/home/node/app/node_modules/@google-cloud/logging/build/src/metadata.js:139:17)
    at async Log.write (/home/node/app/node_modules/@google-cloud/logging/build/src/log.js:177:30) {
  response: {
    config: {
      url: 'http://169.254.169.254/computeMetadata/v1/instance',
      headers: [Object],
      retryConfig: [Object],
      responseType: 'text',
      timeout: 3000,
      params: [Object: null prototype] {},
      paramsSerializer: [Function: paramsSerializer],
      validateStatus: [Function: validateStatus],
      method: 'GET'
    },
    data: 'not found',
    headers: {
      connection: 'close',
      'content-length': '9',
      'content-type': 'text/plain; charset=utf-8',
      date: 'Sat, 14 Sep 2019 16:30:51 GMT'
    },
    status: 404,
    statusText: 'Not Found'
  },
  config: {
    url: 'http://169.254.169.254/computeMetadata/v1/instance',
    headers: { 'Metadata-Flavor': 'Google' },
    retryConfig: {
      noResponseRetries: 0,
      currentRetryAttempt: 0,
      retry: 3,
      retryDelay: 100,
      httpMethodsToRetry: [Array],
      statusCodesToRetry: [Array]
    },
    responseType: 'text',
    timeout: 3000,
    params: [Object: null prototype] {},
    paramsSerializer: [Function: paramsSerializer],
    validateStatus: [Function: validateStatus],
    method: 'GET'
  },
  code: '404'
}`

**Comment by bcoe** [comment]
@noguilty4you until we land a fix (hopefully tomorrow) you can work around this issue by setting a resource type when writing a log:

```js
log.write(entry, {
  resource: {
    type: 'global'
  }
})
```

**Comment by soldair** [comment]
closing this for now as it should be resolved. please check here for confirmation https://github.com/googleapis/gcp-metadata/issues/238 and feel free to reopen if we missed anything

**Comment by noguilty4you** [comment]
@soldair, I am still experiencing the issue - it is unable to connect for at least 1 week.

K8S provider: Yandex.Cloud

Error message
`Uncaught exception, FetchError: Response timeout while trying to fetch http://169.254.169.254/computeMetadata/v1/instance (over 3000ms) FetchError: Response timeout while trying to fetch http://169.254.169.254/computeMetadata/v1/instance (over 3000ms)
    at Timeout._onTimeout (/app/node_modules/node-fetch/lib/index.js:387:12)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)`
